# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marketplace_pb2 as marketplace__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in marketplace_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerDBServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/marketplace.CustomerDBService/Ping',
                request_serializer=marketplace__pb2.Empty.SerializeToString,
                response_deserializer=marketplace__pb2.PingResponse.FromString,
                _registered_method=True)
        self.CreateBuyer = channel.unary_unary(
                '/marketplace.CustomerDBService/CreateBuyer',
                request_serializer=marketplace__pb2.CreateBuyerRequest.SerializeToString,
                response_deserializer=marketplace__pb2.CreateBuyerResponse.FromString,
                _registered_method=True)
        self.CreateSeller = channel.unary_unary(
                '/marketplace.CustomerDBService/CreateSeller',
                request_serializer=marketplace__pb2.CreateSellerRequest.SerializeToString,
                response_deserializer=marketplace__pb2.CreateSellerResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/marketplace.CustomerDBService/Login',
                request_serializer=marketplace__pb2.LoginRequest.SerializeToString,
                response_deserializer=marketplace__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/marketplace.CustomerDBService/Logout',
                request_serializer=marketplace__pb2.LogoutRequest.SerializeToString,
                response_deserializer=marketplace__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.ValidateSession = channel.unary_unary(
                '/marketplace.CustomerDBService/ValidateSession',
                request_serializer=marketplace__pb2.ValidateSessionRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ValidateSessionResponse.FromString,
                _registered_method=True)
        self.GetSellerRating = channel.unary_unary(
                '/marketplace.CustomerDBService/GetSellerRating',
                request_serializer=marketplace__pb2.GetSellerRatingRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetSellerRatingResponse.FromString,
                _registered_method=True)
        self.GetBuyerPurchases = channel.unary_unary(
                '/marketplace.CustomerDBService/GetBuyerPurchases',
                request_serializer=marketplace__pb2.GetBuyerPurchasesRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetBuyerPurchasesResponse.FromString,
                _registered_method=True)
        self.GetCart = channel.unary_unary(
                '/marketplace.CustomerDBService/GetCart',
                request_serializer=marketplace__pb2.GetCartRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetCartResponse.FromString,
                _registered_method=True)
        self.UpdateCart = channel.unary_unary(
                '/marketplace.CustomerDBService/UpdateCart',
                request_serializer=marketplace__pb2.UpdateCartRequest.SerializeToString,
                response_deserializer=marketplace__pb2.UpdateCartResponse.FromString,
                _registered_method=True)
        self.ClearCart = channel.unary_unary(
                '/marketplace.CustomerDBService/ClearCart',
                request_serializer=marketplace__pb2.ClearCartRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ClearCartResponse.FromString,
                _registered_method=True)
        self.SaveCart = channel.unary_unary(
                '/marketplace.CustomerDBService/SaveCart',
                request_serializer=marketplace__pb2.SaveCartRequest.SerializeToString,
                response_deserializer=marketplace__pb2.SaveCartResponse.FromString,
                _registered_method=True)


class CustomerDBServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBuyer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSellerRating(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBuyerPurchases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerDBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=marketplace__pb2.Empty.FromString,
                    response_serializer=marketplace__pb2.PingResponse.SerializeToString,
            ),
            'CreateBuyer': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBuyer,
                    request_deserializer=marketplace__pb2.CreateBuyerRequest.FromString,
                    response_serializer=marketplace__pb2.CreateBuyerResponse.SerializeToString,
            ),
            'CreateSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSeller,
                    request_deserializer=marketplace__pb2.CreateSellerRequest.FromString,
                    response_serializer=marketplace__pb2.CreateSellerResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=marketplace__pb2.LoginRequest.FromString,
                    response_serializer=marketplace__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=marketplace__pb2.LogoutRequest.FromString,
                    response_serializer=marketplace__pb2.LogoutResponse.SerializeToString,
            ),
            'ValidateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSession,
                    request_deserializer=marketplace__pb2.ValidateSessionRequest.FromString,
                    response_serializer=marketplace__pb2.ValidateSessionResponse.SerializeToString,
            ),
            'GetSellerRating': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSellerRating,
                    request_deserializer=marketplace__pb2.GetSellerRatingRequest.FromString,
                    response_serializer=marketplace__pb2.GetSellerRatingResponse.SerializeToString,
            ),
            'GetBuyerPurchases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBuyerPurchases,
                    request_deserializer=marketplace__pb2.GetBuyerPurchasesRequest.FromString,
                    response_serializer=marketplace__pb2.GetBuyerPurchasesResponse.SerializeToString,
            ),
            'GetCart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCart,
                    request_deserializer=marketplace__pb2.GetCartRequest.FromString,
                    response_serializer=marketplace__pb2.GetCartResponse.SerializeToString,
            ),
            'UpdateCart': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCart,
                    request_deserializer=marketplace__pb2.UpdateCartRequest.FromString,
                    response_serializer=marketplace__pb2.UpdateCartResponse.SerializeToString,
            ),
            'ClearCart': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearCart,
                    request_deserializer=marketplace__pb2.ClearCartRequest.FromString,
                    response_serializer=marketplace__pb2.ClearCartResponse.SerializeToString,
            ),
            'SaveCart': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCart,
                    request_deserializer=marketplace__pb2.SaveCartRequest.FromString,
                    response_serializer=marketplace__pb2.SaveCartResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.CustomerDBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.CustomerDBService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerDBService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/Ping',
            marketplace__pb2.Empty.SerializeToString,
            marketplace__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBuyer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/CreateBuyer',
            marketplace__pb2.CreateBuyerRequest.SerializeToString,
            marketplace__pb2.CreateBuyerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/CreateSeller',
            marketplace__pb2.CreateSellerRequest.SerializeToString,
            marketplace__pb2.CreateSellerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/Login',
            marketplace__pb2.LoginRequest.SerializeToString,
            marketplace__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/Logout',
            marketplace__pb2.LogoutRequest.SerializeToString,
            marketplace__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/ValidateSession',
            marketplace__pb2.ValidateSessionRequest.SerializeToString,
            marketplace__pb2.ValidateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSellerRating(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/GetSellerRating',
            marketplace__pb2.GetSellerRatingRequest.SerializeToString,
            marketplace__pb2.GetSellerRatingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBuyerPurchases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/GetBuyerPurchases',
            marketplace__pb2.GetBuyerPurchasesRequest.SerializeToString,
            marketplace__pb2.GetBuyerPurchasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/GetCart',
            marketplace__pb2.GetCartRequest.SerializeToString,
            marketplace__pb2.GetCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/UpdateCart',
            marketplace__pb2.UpdateCartRequest.SerializeToString,
            marketplace__pb2.UpdateCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/ClearCart',
            marketplace__pb2.ClearCartRequest.SerializeToString,
            marketplace__pb2.ClearCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.CustomerDBService/SaveCart',
            marketplace__pb2.SaveCartRequest.SerializeToString,
            marketplace__pb2.SaveCartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProductDBServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/marketplace.ProductDBService/Ping',
                request_serializer=marketplace__pb2.Empty.SerializeToString,
                response_deserializer=marketplace__pb2.PingResponse.FromString,
                _registered_method=True)
        self.RegisterItem = channel.unary_unary(
                '/marketplace.ProductDBService/RegisterItem',
                request_serializer=marketplace__pb2.RegisterItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.RegisterItemResponse.FromString,
                _registered_method=True)
        self.ChangeItemPrice = channel.unary_unary(
                '/marketplace.ProductDBService/ChangeItemPrice',
                request_serializer=marketplace__pb2.ChangeItemPriceRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ChangeItemPriceResponse.FromString,
                _registered_method=True)
        self.UpdateUnitsForSale = channel.unary_unary(
                '/marketplace.ProductDBService/UpdateUnitsForSale',
                request_serializer=marketplace__pb2.UpdateUnitsForSaleRequest.SerializeToString,
                response_deserializer=marketplace__pb2.UpdateUnitsForSaleResponse.FromString,
                _registered_method=True)
        self.DisplayItemsForSale = channel.unary_unary(
                '/marketplace.ProductDBService/DisplayItemsForSale',
                request_serializer=marketplace__pb2.DisplayItemsForSaleRequest.SerializeToString,
                response_deserializer=marketplace__pb2.DisplayItemsForSaleResponse.FromString,
                _registered_method=True)
        self.SearchItems = channel.unary_unary(
                '/marketplace.ProductDBService/SearchItems',
                request_serializer=marketplace__pb2.SearchItemsRequest.SerializeToString,
                response_deserializer=marketplace__pb2.SearchItemsResponse.FromString,
                _registered_method=True)
        self.GetItem = channel.unary_unary(
                '/marketplace.ProductDBService/GetItem',
                request_serializer=marketplace__pb2.GetItemRequest.SerializeToString,
                response_deserializer=marketplace__pb2.GetItemResponse.FromString,
                _registered_method=True)
        self.ProvideFeedback = channel.unary_unary(
                '/marketplace.ProductDBService/ProvideFeedback',
                request_serializer=marketplace__pb2.ProvideFeedbackRequest.SerializeToString,
                response_deserializer=marketplace__pb2.ProvideFeedbackResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/marketplace.ProductDBService/CheckAvailability',
                request_serializer=marketplace__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=marketplace__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)


class ProductDBServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeItemPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnitsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplayItemsForSale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProvideFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductDBServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=marketplace__pb2.Empty.FromString,
                    response_serializer=marketplace__pb2.PingResponse.SerializeToString,
            ),
            'RegisterItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterItem,
                    request_deserializer=marketplace__pb2.RegisterItemRequest.FromString,
                    response_serializer=marketplace__pb2.RegisterItemResponse.SerializeToString,
            ),
            'ChangeItemPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeItemPrice,
                    request_deserializer=marketplace__pb2.ChangeItemPriceRequest.FromString,
                    response_serializer=marketplace__pb2.ChangeItemPriceResponse.SerializeToString,
            ),
            'UpdateUnitsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnitsForSale,
                    request_deserializer=marketplace__pb2.UpdateUnitsForSaleRequest.FromString,
                    response_serializer=marketplace__pb2.UpdateUnitsForSaleResponse.SerializeToString,
            ),
            'DisplayItemsForSale': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplayItemsForSale,
                    request_deserializer=marketplace__pb2.DisplayItemsForSaleRequest.FromString,
                    response_serializer=marketplace__pb2.DisplayItemsForSaleResponse.SerializeToString,
            ),
            'SearchItems': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItems,
                    request_deserializer=marketplace__pb2.SearchItemsRequest.FromString,
                    response_serializer=marketplace__pb2.SearchItemsResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=marketplace__pb2.GetItemRequest.FromString,
                    response_serializer=marketplace__pb2.GetItemResponse.SerializeToString,
            ),
            'ProvideFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProvideFeedback,
                    request_deserializer=marketplace__pb2.ProvideFeedbackRequest.FromString,
                    response_serializer=marketplace__pb2.ProvideFeedbackResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=marketplace__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=marketplace__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketplace.ProductDBService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketplace.ProductDBService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductDBService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/Ping',
            marketplace__pb2.Empty.SerializeToString,
            marketplace__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/RegisterItem',
            marketplace__pb2.RegisterItemRequest.SerializeToString,
            marketplace__pb2.RegisterItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChangeItemPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/ChangeItemPrice',
            marketplace__pb2.ChangeItemPriceRequest.SerializeToString,
            marketplace__pb2.ChangeItemPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnitsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/UpdateUnitsForSale',
            marketplace__pb2.UpdateUnitsForSaleRequest.SerializeToString,
            marketplace__pb2.UpdateUnitsForSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisplayItemsForSale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/DisplayItemsForSale',
            marketplace__pb2.DisplayItemsForSaleRequest.SerializeToString,
            marketplace__pb2.DisplayItemsForSaleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/SearchItems',
            marketplace__pb2.SearchItemsRequest.SerializeToString,
            marketplace__pb2.SearchItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/GetItem',
            marketplace__pb2.GetItemRequest.SerializeToString,
            marketplace__pb2.GetItemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProvideFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/ProvideFeedback',
            marketplace__pb2.ProvideFeedbackRequest.SerializeToString,
            marketplace__pb2.ProvideFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketplace.ProductDBService/CheckAvailability',
            marketplace__pb2.CheckAvailabilityRequest.SerializeToString,
            marketplace__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
